# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 11155111
  start_block: 0
  contracts:
  - name: VybePredictionMarket
    address:
    - 0x62B1885Ae883C48011c1F65F15feb17cfA6b4c19
    handler: src/EventHandlers.ts
    events:
    - event: BetPlaced(uint256 indexed marketId, address indexed user, bool yes, uint256 amount)
    - event: MarketCreated(uint256 indexed marketId, string question, string trackId, uint256 threshold, uint256 deadline)
    - event: Redeemed(uint256 indexed marketId, address indexed user, uint256 payout)
    - event: Resolved(uint256 indexed marketId, bool outcomeYes, uint256 yesPool, uint256 noPool)
unordered_multichain_mode: true
preload_handlers: true
